hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  connection-timeout: 20000
  eureka:
    enabled: true

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: coupons
        url: /coupons/v3/api-docs
      - name: admin
        url: /admin/v3/api-docs
      - name: users
        url: /users/v3/api-docs
      - name: company
        url: /company/v3/api-docs
      - name: zuul
        url: /v3/api-docs


zuul:
  routes:
    coupons-service:
      path: /coupons/**
      serviceId: coupons-service
    admin-service:
      path: /admin/**
      serviceId: admin-service
    user-service:
      path: /users/**
      serviceId: user-service
    company-service:
      path: /company/**
      serviceId: company-service