zuul:
  routes:
    admin:
      url: http://localhost:3500/admin/
    company:
      url: http://localhost:3800/company/
    coupons:
      url: http://localhost:2500/coupons/


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS